theme: jekyll-theme-minimal
title: Emily Chen
logo: /assets/images/plumpthink.png
description: Applied Cognition and Neuroscience student at the University of Texas at Dallas.
show_downloads: true
google_analytics:
baseurl: /emilc-jpg.github.io
